name: Kids Future Jobs (Sun)

on:
  schedule:
    # JST 日曜 08:00 = UTC 土曜 23:00
    - cron: '0 23 * * 6'
  workflow_dispatch: {}

jobs:
  autopost:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      WP_URL: ${{ secrets.WP_URL }}
      WP_USER: ${{ secrets.WP_USER }}
      WP_APP_PASS: ${{ secrets.WP_APP_PASS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install openai requests feedparser pillow python-dateutil markdown-it-py markdown

      - name: Fetch latest news
        run: python scripts/fetch_news_kids_jobs.py

      - name: Generate article
        run: python scripts/gen_article_news_kids_jobs.py

      - name: Commit markdown
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add posts/news/kids_jobs/*.md
          git commit -m "auto: newsIF $(date -u '+%Y-%m-%d')" || echo "nothing to commit"
          git pull origin main --rebase --autostash || echo "rebase failed"
          git push origin HEAD:main || echo "push failed"

      - name: Post to WordPress
        run: python scripts/post_to_wp_kids_jobs.py
